# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

let
  ibm_plymouth_theme = pkgs.callPackage ./plymouth/ibm.nix { };
in
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    loader = {
      systemd-boot.enable = pkgs.system == "x86_64-linux";
      efi.canTouchEfiVariables = true;

      grub = {
        # Disable the GNU GRUB boot loader.
        enable = lib.mkForce false;
        # Automatically add other operating system to the grub menu
        useOSProber = true;
      };

    };
    
    # Use the latest Linux kernel packages
    # kernelPackages = pkgs.linuxPackages_latest;

    # Enable plymouth boot splash screen
    plymouth = {
      enable = true;
      theme = "ibm";
      themePackages = [ ibm_plymouth_theme ];
    };
  };
}